// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    // `app/components/ui` holds shadcn-vue components generated by the CLI.
    // Their optional `class` prop is meant to default to undefined so `cn()`
    // can ignore it, and the files are overwritten whenever a component is
    // regenerated, so local edits there do not survive.
    files: ['app/components/ui/**/*.vue'],
    rules: {
      'vue/require-default-prop': 'off',
    },
  },
)
